### PR TITLE
Use `org.jetbrains.annotations.Nullable`

### LINKED ISSUE #22: Use `org.jetbrains.annotations.Nullable`?
I'm thinking about using `org.jetbrains.annotations.Nullable` instead of our own `tech.icey.panama.annotation.nullable`. I'm unclear about Java world best practice yet. @ice1000 any suggestions?

### PR DESCRIPTION
**Pull request by CousinZe**
Closes #22

### CODE REVIEW

**Review by ice1000 — APPROVED** [review]

**Comment by chuigda** [comment]
KEAL.

**Comment by ice1000** [comment]
It's not a good idea to use `@Nullable T` in Kotlin, you should instead use `T?`

**Comment by chuigda** [comment]
> It's not a good idea to use `@Nullable T` in Kotlin, you should instead use `T?`

There's no `@Nullable T` in Kotlin code, but Kotlin code's output.

**Comment by ice1000** [comment]
OOOOOOOOOOOOOoo

**Pull request merged**
